@baseUrl = http://localhost:3000

# Messages

### MessagesControllerGet
# @name MessagesControllerGet
GET {{baseUrl}}/messages/

### MessagesControllerGetById
# @name MessagesControllerGetById
GET {{baseUrl}}/messages/3

### MessagesControllerPost
# @name MessagesControllerPost
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "text": "Test Create Message",
  "from": "Luiz",
  "to": "Luiz"
}

### MessagesControllerPatch
# @name MessagesControllerPatch
PATCH {{baseUrl}}/messages/1
Content-Type: application/json

{
  "text": "Test Update Message",
}

### MessagesControllerDelete
# @name MessagesControllerDelete
DELETE {{baseUrl}}/messages/2